#!/usr/bin/env python

# Import libraries
from pylab import *
import numpy as np
import random
import math

# Parameters of code
start_radius=100
out_of_bounds=150

# Define functions
def find_perimeter(cluster):
        perimeter=[]
        for i in range(-start_radius,start_radius):
                for j in range(-start_radius,start_radius):
                        if

#def check_perimeter(walker,perimeter):
#       find_perimeter()
#       for 



def rand_point_on_circle():
        x=round(random.uniform(-100,100),0)
        y=round(math.sqrt(start_radius**2.0-x**2.0))
        print "x,y:",x,y

        radius=math.sqrt(x**2+y**2)
        print "radius: ",radius
        walker=np.zeros(2)
        walker[0]=x
        walker[1]=y
        return walker
walker=rand_point_on_circle()
#print "prime:", x_prime, y_prime
print walker




# Declare variables
cluster=np.zeros((int(start_radius+1),int(start_radius+1)))
#cluster=np.zeros((int(start_radius+1)),(int(start_radius+1)))
cluster[100][0]=1
print cluster


# Loop over random walkers until the cluster radius, r, is 100 
r=0
while r >= 100:
        walker=rand_point_on_circle()
        rand_num=random.uniform(0,1)
        if rand_num =<0.25:
                walker[0]+=1
        elif rand_num > 0.25 and rand_num <= 0.50:
                walker[0]-=1
        elif rand_num >0.50 and rand_num <= 0.75:
                walker[1]+=1
        elif rand_num >0.75:
                walker[1]-=1

        # Check perimeter sites
        find_perimeter

